name: Deploy new hugo build to Cloud Environment
on:
  push:
    branches:
      - master
jobs:
  DeploytoCloudformation:
    runs-on: ubuntu-latest
    steps:
      - name: Get Source Code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: '${{ secrets.AWS_REGION_ID }}'

      - name: setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: Hugo Build
        working-directory: ./
        run: hugo

      - name: Deploy
        run: |
          ls
          echo "====="
          ls public
          aws s3 sync --acl public-read ./public s3://${{ secrets.S3BUCKET_NAME }} --delete

      - name: Create Invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"